platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PokedexDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokedexDemo

  pod 'RxSwift'                                   ,   :inhibit_warnings => true
  pod 'RxSwiftExt'                                ,   :inhibit_warnings => true
  pod 'RxCocoa'                                   ,   :inhibit_warnings => true

  target 'PokedexDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokedexDemoUITests' do
    # Pods for testing
  end

end
